In [20]:
import os
import pandas as pd

# Define the root folder
root_folder = "smartbugs-curated-v2"  # Change this to your target folder

# Initialize a list to store data
data = []

# Walk through the directory
for subdir, _, files in os.walk(root_folder):
    subfolder_name = os.path.basename(subdir)  # Get the name of the subfolder
    for file in files:
        if ".sol" in file:
            data.append([subfolder_name, file])

# Create DataFrame
df = pd.DataFrame(data, columns=["subfolder", "filename"])

In [22]:
df

                     subfolder                             filename
0               access_control  arbitrary_location_write_simple.sol
1               access_control                 FibonacciBalance.sol
2               access_control      incorrect_constructor_name1.sol
3               access_control      incorrect_constructor_name2.sol
4               access_control      incorrect_constructor_name3.sol
..                         ...                                  ...
142  unchecked_low_level_calls                   etherpot_lotto.sol
143  unchecked_low_level_calls         king_of_the_ether_throne.sol
144  unchecked_low_level_calls                            lotto.sol
145  unchecked_low_level_calls                       mishandled.sol
146  unchecked_low_level_calls           unchecked_return_value.sol

[147 rows x 2 columns]

In [24]:
import re

cwd = os.getcwd()
parent_folder = f"{cwd}\\smartbugs-curated-v2"

def extract_vulnerable_lines(source_code):
    match = re.search(r'@vulnerable_at_lines:\s*([\d,\s]+)', source_code)
    if match:
        line_numbers = set(map(int, match.group(1).split(',')))
        return line_numbers
    return set()

def read_file(path):
    with open(path, 'r', encoding='utf-8') as file:
        return file.read()

def extract_and_update_vulnerable_lines_in_df(df):
    df['source_code'] = None
    df['vuln_lines'] = None
    for index, row in df.iterrows():
        file_path = f"{parent_folder}\\{row['subfolder']}\\{row['filename']}"
        content = read_file(file_path)
        if content is not None:
            line_numbers = extract_vulnerable_lines(content)
            if len(line_numbers) > 0:
                df.loc[index, "source_code"] = content
                df.loc[index, "vuln_lines"] = str(line_numbers)
                print(f"Success: {file_path} - {str(line_numbers)}")
            else:
                print(f"Something went wrong: empty line numbers set for {file_path}")
        else:
            print(f"Something went wrong: empty source code for {file_path}")

In [26]:
extract_and_update_vulnerable_lines_in_df(df)

Success: D:\UoM\Final_Year_Project_New\vulnerability-detection-and-localization\datasets\smartbugs-curated-v2\access_control\arbitrary_location_write_simple.sol - {27}
Success: D:\UoM\Final_Year_Project_New\vulnerability-detection-and-localization\datasets\smartbugs-curated-v2\access_control\FibonacciBalance.sol - {38, 31}
Success: D:\UoM\Final_Year_Project_New\vulnerability-detection-and-localization\datasets\smartbugs-curated-v2\access_control\incorrect_constructor_name1.sol - {20}
Success: D:\UoM\Final_Year_Project_New\vulnerability-detection-and-localization\datasets\smartbugs-curated-v2\access_control\incorrect_constructor_name2.sol - {18}
Success: D:\UoM\Final_Year_Project_New\vulnerability-detection-and-localization\datasets\smartbugs-curated-v2\access_control\incorrect_constructor_name3.sol - {17}
Success: D:\UoM\Final_Year_Project_New\vulnerability-detection-and-localization\datasets\smartbugs-curated-v2\access_control\mapping_write.sol - {20}
Success: D:\UoM\Final_Year_Project_New\vulnerability-detection-and-localization\datasets\smartbugs-curated-v2\access_control\multiowned_vulnerable.sol - {38}
Success: D:\UoM\Final_Year_Project_New\vulnerability-detection-and-localization\datasets\smartbugs-curated-v2\access_control\mycontract.sol - {20}
Success: D:\UoM\Final_Year_Project_New\vulnerability-detection-and-localization\datasets\smartbugs-curated-v2\access_control\parity_wallet_bug_1.sol - {437, 223}
Success: D:\UoM\Final_Year_Project_New\vulnerability-detection-and-localization\datasets\smartbugs-curated-v2\access_control\parity_wallet_bug_2.sol - {233, 226}
Success: D:\UoM\Final_Year_Project_New\vulnerability-detection-and-localization\datasets\smartbugs-curated-v2\access_control\phishable.sol - {20}
Success: D:\UoM\Final_Year_Project_New\vulnerability-detection-and-localization\datasets\smartbugs-curated-v2\access_control\proxy.sol - {19}
Success: D:\UoM\Final_Year_Project_New\vulnerability-detection-and-localization\datasets\smartbugs-curated-v2\access_control\rubixi.sol - {24, 23}
Success: D:\UoM\Final_Year_Project_New\vulnerability-detection-and-localization\datasets\smartbugs-curated-v2\access_control\simple_suicide.sol - {12, 13}
Success: D:\UoM\Final_Year_Project_New\vulnerability-detection-and-localization\datasets\smartbugs-curated-v2\access_control\unprotected0.sol - {25}
Success: D:\UoM\Final_Year_Project_New\vulnerability-detection-and-localization\datasets\smartbugs-curated-v2\access_control\wallet_02_refund_nosub.sol - {36}
Success: D:\UoM\Final_Year_Project_New\vulnerability-detection-and-localization\datasets\smartbugs-curated-v2\access_control\wallet_03_wrong_constructor.sol - {19, 20}
Success: D:\UoM\Final_Year_Project_New\vulnerability-detection-and-localization\datasets\smartbugs-curated-v2\access_control\wallet_04_confused_sign.sol - {30}
Success: D:\UoM\Final_Year_Project_New\vulnerability-detection-and-localization\datasets\smartbugs-curated-v2\arithmetic\BECToken.sol - {264}
Success: D:\UoM\Final_Year_Project_New\vulnerability-detection-and-localization\datasets\smartbugs-curated-v2\arithmetic\insecure_transfer.sol - {18}
Success: D:\UoM\Final_Year_Project_New\vulnerability-detection-and-localization\datasets\smartbugs-curated-v2\arithmetic\integer_overflow_1.sol - {14}
Success: D:\UoM\Final_Year_Project_New\vulnerability-detection-and-localization\datasets\smartbugs-curated-v2\arithmetic\integer_overflow_add.sol - {17}
Success: D:\UoM\Final_Year_Project_New\vulnerability-detection-and-localization\datasets\smartbugs-curated-v2\arithmetic\integer_overflow_benign_1.sol - {17}
Success: D:\UoM\Final_Year_Project_New\vulnerability-detection-and-localization\datasets\smartbugs-curated-v2\arithmetic\integer_overflow_mapping_sym_1.sol - {16}
Success: D:\UoM\Final_Year_Project_New\vulnerability-detection-and-localization\datasets\smartbugs-curated-v2\arithmetic\integer_overflow_minimal.sol - {17}
Success: D:\UoM\Final_Year_Project_New\vulnerability-detection-and-localization\datasets\smartbugs-curated-v2\arithmetic\integer_overflow_mul.sol - {17}
Success: D:\UoM\Final_Year_Project_New\vulnerability-detection-and-localization\datasets\smartbugs-curated-v2\arithmetic\integer_overflow_multitx_multifunc_feasible.sol - {25}
Success: D:\UoM\Final_Year_Project_New\vulnerability-detection-and-localization\datasets\smartbugs-curated-v2\arithmetic\integer_overflow_multitx_onefunc_feasible.sol - {22}
Success: D:\UoM\Final_Year_Project_New\vulnerability-detection-and-localization\datasets\smartbugs-curated-v2\arithmetic\overflow_simple_add.sol - {14}
Success: D:\UoM\Final_Year_Project_New\vulnerability-detection-and-localization\datasets\smartbugs-curated-v2\arithmetic\overflow_single_tx.sol - {36, 42, 48, 18, 24, 30}
Success: D:\UoM\Final_Year_Project_New\vulnerability-detection-and-localization\datasets\smartbugs-curated-v2\arithmetic\timelock.sol - {22}
Success: D:\UoM\Final_Year_Project_New\vulnerability-detection-and-localization\datasets\smartbugs-curated-v2\arithmetic\token.sol - {20, 22}
Success: D:\UoM\Final_Year_Project_New\vulnerability-detection-and-localization\datasets\smartbugs-curated-v2\arithmetic\tokensalechallenge.sol - {25, 33, 23}
Success: D:\UoM\Final_Year_Project_New\vulnerability-detection-and-localization\datasets\smartbugs-curated-v2\bad_randomness\blackjack.sol - {17, 19, 21}
Success: D:\UoM\Final_Year_Project_New\vulnerability-detection-and-localization\datasets\smartbugs-curated-v2\bad_randomness\etheraffle.sol - {99, 101, 103, 49, 114, 158}
Success: D:\UoM\Final_Year_Project_New\vulnerability-detection-and-localization\datasets\smartbugs-curated-v2\bad_randomness\guess_the_random_number.sol - {15}
Success: D:\UoM\Final_Year_Project_New\vulnerability-detection-and-localization\datasets\smartbugs-curated-v2\bad_randomness\lottery.sol - {42, 38}
Success: D:\UoM\Final_Year_Project_New\vulnerability-detection-and-localization\datasets\smartbugs-curated-v2\bad_randomness\lucky_doubler.sol - {128, 129, 130, 132, 127}
Success: D:\UoM\Final_Year_Project_New\vulnerability-detection-and-localization\datasets\smartbugs-curated-v2\bad_randomness\old_blockhash.sol - {35}
Success: D:\UoM\Final_Year_Project_New\vulnerability-detection-and-localization\datasets\smartbugs-curated-v2\bad_randomness\random_number_generator.sol - {18, 12, 20, 22}
Success: D:\UoM\Final_Year_Project_New\vulnerability-detection-and-localization\datasets\smartbugs-curated-v2\bad_randomness\smart_billions.sol - {704, 706, 708, 710, 712, 714, 523, 716, 718, 560, 700, 702}
Success: D:\UoM\Final_Year_Project_New\vulnerability-detection-and-localization\datasets\smartbugs-curated-v2\denial_of_service\auction.sol - {23}
Success: D:\UoM\Final_Year_Project_New\vulnerability-detection-and-localization\datasets\smartbugs-curated-v2\denial_of_service\dos_address.sol - {16, 17, 18}
Success: D:\UoM\Final_Year_Project_New\vulnerability-detection-and-localization\datasets\smartbugs-curated-v2\denial_of_service\dos_number.sol - {18, 19, 20, 21, 22}
Success: D:\UoM\Final_Year_Project_New\vulnerability-detection-and-localization\datasets\smartbugs-curated-v2\denial_of_service\dos_simple.sol - {17, 18}
Success: D:\UoM\Final_Year_Project_New\vulnerability-detection-and-localization\datasets\smartbugs-curated-v2\denial_of_service\list_dos.sol - {48, 46}
Success: D:\UoM\Final_Year_Project_New\vulnerability-detection-and-localization\datasets\smartbugs-curated-v2\denial_of_service\send_loop.sol - {24}
Success: D:\UoM\Final_Year_Project_New\vulnerability-detection-and-localization\datasets\smartbugs-curated-v2\front_running\ERC20.sol - {113, 110}
Success: D:\UoM\Final_Year_Project_New\vulnerability-detection-and-localization\datasets\smartbugs-curated-v2\front_running\eth_tx_order_dependence_minimal.sol - {31, 23}
Success: D:\UoM\Final_Year_Project_New\vulnerability-detection-and-localization\datasets\smartbugs-curated-v2\front_running\FindThisHash.sol - {17}
Success: D:\UoM\Final_Year_Project_New\vulnerability-detection-and-localization\datasets\smartbugs-curated-v2\front_running\odds_and_evens.sol - {25, 28}
Success: D:\UoM\Final_Year_Project_New\vulnerability-detection-and-localization\datasets\smartbugs-curated-v2\other\crypto_roulette.sol - {40, 41, 42}
Success: D:\UoM\Final_Year_Project_New\vulnerability-detection-and-localization\datasets\smartbugs-curated-v2\other\name_registrar.sol - {21}
Success: D:\UoM\Final_Year_Project_New\vulnerability-detection-and-localization\datasets\smartbugs-curated-v2\other\open_address_lottery.sol - {91}
Success: D:\UoM\Final_Year_Project_New\vulnerability-detection-and-localization\datasets\smartbugs-curated-v2\reentrancy\0x01f8c4e3fa3edeb29e514cba738d87ce8c091d3f.sol - {56, 54}
Success: D:\UoM\Final_Year_Project_New\vulnerability-detection-and-localization\datasets\smartbugs-curated-v2\reentrancy\0x23a91059fdc9579a9fbd0edc5f2ea0bfdb70deb4.sol - {40, 38}
Success: D:\UoM\Final_Year_Project_New\vulnerability-detection-and-localization\datasets\smartbugs-curated-v2\reentrancy\0x4320e6f8c05b27ab4707cd1f6d5ce6f3e4b3a5a1.sol - {57, 55}
Success: D:\UoM\Final_Year_Project_New\vulnerability-detection-and-localization\datasets\smartbugs-curated-v2\reentrancy\0x4e73b32ed6c35f570686b89848e5f39f20ecc106.sol - {56, 54}
Success: D:\UoM\Final_Year_Project_New\vulnerability-detection-and-localization\datasets\smartbugs-curated-v2\reentrancy\0x561eac93c92360949ab1f1403323e6db345cbf31.sol - {56, 54}
Success: D:\UoM\Final_Year_Project_New\vulnerability-detection-and-localization\datasets\smartbugs-curated-v2\reentrancy\0x627fa62ccbb1c1b04ffaecd72a53e37fc0e17839.sol - {96, 94}
Success: D:\UoM\Final_Year_Project_New\vulnerability-detection-and-localization\datasets\smartbugs-curated-v2\reentrancy\0x7541b76cb60f4c60af330c208b0623b7f54bf615.sol - {29, 31}
Success: D:\UoM\Final_Year_Project_New\vulnerability-detection-and-localization\datasets\smartbugs-curated-v2\reentrancy\0x7a8721a9d64c74da899424c1b52acbf58ddc9782.sol - {52, 54}
Success: D:\UoM\Final_Year_Project_New\vulnerability-detection-and-localization\datasets\smartbugs-curated-v2\reentrancy\0x7b368c4e805c3870b6c49a3f1f49f69af8662cf3.sol - {29, 31}
Success: D:\UoM\Final_Year_Project_New\vulnerability-detection-and-localization\datasets\smartbugs-curated-v2\reentrancy\0x8c7777c45481dba411450c228cb692ac3d550344.sol - {41, 43}
Success: D:\UoM\Final_Year_Project_New\vulnerability-detection-and-localization\datasets\smartbugs-curated-v2\reentrancy\0x93c32845fae42c83a70e5f06214c8433665c2ab5.sol - {29, 31}
Success: D:\UoM\Final_Year_Project_New\vulnerability-detection-and-localization\datasets\smartbugs-curated-v2\reentrancy\0x941d225236464a25eb18076df7da6a91d0f95e9e.sol - {44, 46}
Success: D:\UoM\Final_Year_Project_New\vulnerability-detection-and-localization\datasets\smartbugs-curated-v2\reentrancy\0x96edbe868531bd23a6c05e9d0c424ea64fb1b78b.sol - {65, 63}
Success: D:\UoM\Final_Year_Project_New\vulnerability-detection-and-localization\datasets\smartbugs-curated-v2\reentrancy\0xaae1f51cf3339f18b6d3f3bdc75a5facd744b0b8.sol - {56, 54}
Success: D:\UoM\Final_Year_Project_New\vulnerability-detection-and-localization\datasets\smartbugs-curated-v2\reentrancy\0xb5e1b1ee15c6fa0e48fce100125569d430f1bd12.sol - {40, 42}
Success: D:\UoM\Final_Year_Project_New\vulnerability-detection-and-localization\datasets\smartbugs-curated-v2\reentrancy\0xb93430ce38ac4a6bb47fb1fc085ea669353fd89e.sol - {40, 38}
Success: D:\UoM\Final_Year_Project_New\vulnerability-detection-and-localization\datasets\smartbugs-curated-v2\reentrancy\0xbaf51e761510c1a11bf48dd87c0307ac8a8c8a4f.sol - {41, 43}
Success: D:\UoM\Final_Year_Project_New\vulnerability-detection-and-localization\datasets\smartbugs-curated-v2\reentrancy\0xbe4041d55db380c5ae9d4a9b9703f1ed4e7e3888.sol - {65, 63}
Success: D:\UoM\Final_Year_Project_New\vulnerability-detection-and-localization\datasets\smartbugs-curated-v2\reentrancy\0xcead721ef5b11f1a7b530171aab69b16c5e66b6e.sol - {29, 31}
Success: D:\UoM\Final_Year_Project_New\vulnerability-detection-and-localization\datasets\smartbugs-curated-v2\reentrancy\0xf015c35649c82f5467c9c74b7f28ee67665aad68.sol - {29, 31}
Success: D:\UoM\Final_Year_Project_New\vulnerability-detection-and-localization\datasets\smartbugs-curated-v2\reentrancy\etherbank.sol - {21, 22}
Success: D:\UoM\Final_Year_Project_New\vulnerability-detection-and-localization\datasets\smartbugs-curated-v2\reentrancy\etherstore.sol - {27, 28}
Success: D:\UoM\Final_Year_Project_New\vulnerability-detection-and-localization\datasets\smartbugs-curated-v2\reentrancy\modifier_reentrancy.sol - {16, 15}
Success: D:\UoM\Final_Year_Project_New\vulnerability-detection-and-localization\datasets\smartbugs-curated-v2\reentrancy\reentrance.sol - {24, 27}
Success: D:\UoM\Final_Year_Project_New\vulnerability-detection-and-localization\datasets\smartbugs-curated-v2\reentrancy\reentrancy_bonus.sol - {28}
Success: D:\UoM\Final_Year_Project_New\vulnerability-detection-and-localization\datasets\smartbugs-curated-v2\reentrancy\reentrancy_cross_function.sol - {24}
Success: D:\UoM\Final_Year_Project_New\vulnerability-detection-and-localization\datasets\smartbugs-curated-v2\reentrancy\reentrancy_dao.sol - {18, 19}
Success: D:\UoM\Final_Year_Project_New\vulnerability-detection-and-localization\datasets\smartbugs-curated-v2\reentrancy\reentrancy_insecure.sol - {17, 18}
Success: D:\UoM\Final_Year_Project_New\vulnerability-detection-and-localization\datasets\smartbugs-curated-v2\reentrancy\reentrancy_simple.sol - {24, 27}
Success: D:\UoM\Final_Year_Project_New\vulnerability-detection-and-localization\datasets\smartbugs-curated-v2\reentrancy\simple_dao.sol - {17, 19}
Success: D:\UoM\Final_Year_Project_New\vulnerability-detection-and-localization\datasets\smartbugs-curated-v2\reentrancy\spank_chain_payment.sol - {426, 430}
Success: D:\UoM\Final_Year_Project_New\vulnerability-detection-and-localization\datasets\smartbugs-curated-v2\short_addresses\short_address_example.sol - {18}
Success: D:\UoM\Final_Year_Project_New\vulnerability-detection-and-localization\datasets\smartbugs-curated-v2\short_addresses\short_address_example_1.sol - {16}
Success: D:\UoM\Final_Year_Project_New\vulnerability-detection-and-localization\datasets\smartbugs-curated-v2\short_addresses\short_address_example_2.sol - {16}
Success: D:\UoM\Final_Year_Project_New\vulnerability-detection-and-localization\datasets\smartbugs-curated-v2\short_addresses\short_address_example_3.sol - {17}
Success: D:\UoM\Final_Year_Project_New\vulnerability-detection-and-localization\datasets\smartbugs-curated-v2\short_addresses\short_address_example_4.sol - {17}
Success: D:\UoM\Final_Year_Project_New\vulnerability-detection-and-localization\datasets\smartbugs-curated-v2\time_manipulation\ether_lotto.sol - {43}
Success: D:\UoM\Final_Year_Project_New\vulnerability-detection-and-localization\datasets\smartbugs-curated-v2\time_manipulation\governmental_survey.sol - {27}
Success: D:\UoM\Final_Year_Project_New\vulnerability-detection-and-localization\datasets\smartbugs-curated-v2\time_manipulation\lottopollo.sol - {27, 13}
Success: D:\UoM\Final_Year_Project_New\vulnerability-detection-and-localization\datasets\smartbugs-curated-v2\time_manipulation\roulette.sol - {18, 20}
Success: D:\UoM\Final_Year_Project_New\vulnerability-detection-and-localization\datasets\smartbugs-curated-v2\time_manipulation\timed_crowdsale.sol - {13}
Success: D:\UoM\Final_Year_Project_New\vulnerability-detection-and-localization\datasets\smartbugs-curated-v2\unchecked_low_level_calls\0x07f7ecb66d788ab01dc93b9b71a88401de7d0f2e.sol - {201, 213}
Success: D:\UoM\Final_Year_Project_New\vulnerability-detection-and-localization\datasets\smartbugs-curated-v2\unchecked_low_level_calls\0x0cbe050f75bc8f8c2d6c0d249fea125fd6e1acc9.sol - {12}
Success: D:\UoM\Final_Year_Project_New\vulnerability-detection-and-localization\datasets\smartbugs-curated-v2\unchecked_low_level_calls\0x19cf8481ea15427a98ba3cdd6d9e14690011ab10.sol - {465, 439}
Success: D:\UoM\Final_Year_Project_New\vulnerability-detection-and-localization\datasets\smartbugs-curated-v2\unchecked_low_level_calls\0x2972d548497286d18e92b5fa1f8f9139e5653fd2.sol - {14}
Success: D:\UoM\Final_Year_Project_New\vulnerability-detection-and-localization\datasets\smartbugs-curated-v2\unchecked_low_level_calls\0x39cfd754c85023648bf003bea2dd498c5612abfa.sol - {97, 44}
Success: D:\UoM\Final_Year_Project_New\vulnerability-detection-and-localization\datasets\smartbugs-curated-v2\unchecked_low_level_calls\0x3a0e9acd953ffc0dd18d63603488846a6b8b2b01.sol - {97, 44}
Success: D:\UoM\Final_Year_Project_New\vulnerability-detection-and-localization\datasets\smartbugs-curated-v2\unchecked_low_level_calls\0x3e013fc32a54c4c5b6991ba539dcd0ec4355c859.sol - {29}
Success: D:\UoM\Final_Year_Project_New\vulnerability-detection-and-localization\datasets\smartbugs-curated-v2\unchecked_low_level_calls\0x3f2ef511aa6e75231e4deafc7a3d2ecab3741de2.sol - {45}
Success: D:\UoM\Final_Year_Project_New\vulnerability-detection-and-localization\datasets\smartbugs-curated-v2\unchecked_low_level_calls\0x4051334adc52057aca763453820cb0e045076ef3.sol - {16}
Success: D:\UoM\Final_Year_Project_New\vulnerability-detection-and-localization\datasets\smartbugs-curated-v2\unchecked_low_level_calls\0x4a66ad0bca2d700f11e1f2fc2c106f7d3264504c.sol - {19}
Success: D:\UoM\Final_Year_Project_New\vulnerability-detection-and-localization\datasets\smartbugs-curated-v2\unchecked_low_level_calls\0x4b71ad9c1a84b9b643aa54fdd66e2dec96e8b152.sol - {17}
Success: D:\UoM\Final_Year_Project_New\vulnerability-detection-and-localization\datasets\smartbugs-curated-v2\unchecked_low_level_calls\0x524960d55174d912768678d8c606b4d50b79d7b1.sol - {21}
Success: D:\UoM\Final_Year_Project_New\vulnerability-detection-and-localization\datasets\smartbugs-curated-v2\unchecked_low_level_calls\0x52d2e0f9b01101a59b38a3d05c80b7618aeed984.sol - {27}
Success: D:\UoM\Final_Year_Project_New\vulnerability-detection-and-localization\datasets\smartbugs-curated-v2\unchecked_low_level_calls\0x5aa88d2901c68fda244f1d0584400368d2c8e739.sol - {29}
Success: D:\UoM\Final_Year_Project_New\vulnerability-detection-and-localization\datasets\smartbugs-curated-v2\unchecked_low_level_calls\0x610495793564aed0f9c7fc48dc4c7c9151d34fd6.sol - {33}
Success: D:\UoM\Final_Year_Project_New\vulnerability-detection-and-localization\datasets\smartbugs-curated-v2\unchecked_low_level_calls\0x627fa62ccbb1c1b04ffaecd72a53e37fc0e17839.sol - {44}
Success: D:\UoM\Final_Year_Project_New\vulnerability-detection-and-localization\datasets\smartbugs-curated-v2\unchecked_low_level_calls\0x663e4229142a27f00bafb5d087e1e730648314c3.sol - {1152, 2467, 1496}
Success: D:\UoM\Final_Year_Project_New\vulnerability-detection-and-localization\datasets\smartbugs-curated-v2\unchecked_low_level_calls\0x70f9eddb3931491aab1aeafbc1e7f1ca2a012db4.sol - {29}
Success: D:\UoM\Final_Year_Project_New\vulnerability-detection-and-localization\datasets\smartbugs-curated-v2\unchecked_low_level_calls\0x78c2a1e91b52bca4130b6ed9edd9fbcfd4671c37.sol - {45}
Success: D:\UoM\Final_Year_Project_New\vulnerability-detection-and-localization\datasets\smartbugs-curated-v2\unchecked_low_level_calls\0x7a4349a749e59a5736efb7826ee3496a2dfd5489.sol - {44}
Success: D:\UoM\Final_Year_Project_New\vulnerability-detection-and-localization\datasets\smartbugs-curated-v2\unchecked_low_level_calls\0x7d09edb07d23acb532a82be3da5c17d9d85806b4.sol - {210, 198}
Success: D:\UoM\Final_Year_Project_New\vulnerability-detection-and-localization\datasets\smartbugs-curated-v2\unchecked_low_level_calls\0x806a6bd219f162442d992bdc4ee6eba1f2c5a707.sol - {44}
Success: D:\UoM\Final_Year_Project_New\vulnerability-detection-and-localization\datasets\smartbugs-curated-v2\unchecked_low_level_calls\0x84d9ec85c9c568eb332b7226a8f826d897e0a4a8.sol - {56}
Success: D:\UoM\Final_Year_Project_New\vulnerability-detection-and-localization\datasets\smartbugs-curated-v2\unchecked_low_level_calls\0x89c1b3807d4c67df034fffb62f3509561218d30b.sol - {192, 162, 180, 175}

In [28]:
df

,subfolder,filename,source_code,vuln_lines
0,access_control,arbitrary_location_write_simple.sol,/*\n * @source: https://smartcontractsecurity....,{27}
1,access_control,FibonacciBalance.sol,/*\n * @source: https://github.com/sigp/solidi...,"{38, 31}"
2,access_control,incorrect_constructor_name1.sol,/*\n * @source: https://github.com/trailofbits...,{20}
3,access_control,incorrect_constructor_name2.sol,/*\n * @source: https://smartcontractsecurity....,{18}
4,access_control,incorrect_constructor_name3.sol,/*\n * @source: https://smartcontractsecurity....,{17}
...,...,...,...,...
142,unchecked_low_level_calls,etherpot_lotto.sol,/*\n * @source: https://github.com/etherpot/co...,"{109, 141}"
143,unchecked_low_level_calls,king_of_the_ether_throne.sol,/*\n * @source: https://github.com/kieranelby/...,"{118, 132, 174, 110}"
144,unchecked_low_level_calls,lotto.sol,/*\n * @source: https://github.com/sigp/solidi...,"{27, 20}"
145,unchecked_low_level_calls,mishandled.sol,/*\n * @source: https://github.com/seresistvan...,{14}
146,unchecked_low_level_calls,unchecked_return_value.sol,/*\n * @source: https://smartcontractsecurity....,{17}

In [30]:
(df['source_code'] == None).sum()

0

In [32]:
(df['vuln_lines'] == None).sum()

0

In [34]:
!mkdir processed

A subdirectory or file processed already exists.

In [36]:
df.to_csv("processed/smartbugs_curated_dataset_with_vuln_line_numbers_v2.csv")