# Vulnerable-Verified-Smart-Contracts

In [18]:
import pandas as pd
import os

cwd = os.getcwd()

train = pd.read_parquet(f'{cwd}\\Vulnerable-Verified-Smart-Contracts\\train.parquet')
test = pd.read_parquet(f'{cwd}\\Vulnerable-Verified-Smart-Contracts\\test.parquet')
valid = pd.read_parquet(f'{cwd}\\Vulnerable-Verified-Smart-Contracts\\validation.parquet')

In [27]:
print("train:", len(train))
print("test:", len(test))
print("validation:", len(valid))

train: 524
test: 35
validation: 50

In [31]:
print("train:", train.columns.tolist())
print("test:", test.columns.tolist())
print("validation:", valid.columns.tolist())

train: ['contract_name', 'file_path', 'contract_address', 'language', 'source_code', 'overlapping', 'soldetector', 'slither', 'oyente', 'smartcheck', 'compiler_version', 'license_type', 'swarm_source']
test: ['contract_name', 'file_path', 'contract_address', 'language', 'source_code', 'overlapping', 'soldetector', 'slither', 'oyente', 'smartcheck', 'compiler_version', 'license_type', 'swarm_source']
validation: ['contract_name', 'file_path', 'contract_address', 'language', 'source_code', 'overlapping', 'soldetector', 'slither', 'oyente', 'smartcheck', 'compiler_version', 'license_type', 'swarm_source']

In [33]:
display(train)

,contract_name,file_path,contract_address,language,source_code,overlapping,soldetector,slither,oyente,smartcheck,compiler_version,license_type,swarm_source
0,Gift,Gift.sol,0xb91a6c5c6362b10db6440d690e5391bb1eabe591,Solidity,pragma solidity ^0.4.22;\r\n\r\ncontract Gift\...,"{""IOU"": [[{""defect"": ""Integer_overflow_and_und...","[{""defect"": ""Erroneous_constructor_name"", ""typ...","[{""check"": ""external-function"", ""impact"": ""Opt...","[{""error"": ""Integer Overflow."", ""line"": 14, ""l...","[{""rule"": ""SOLIDITY_PRAGMAS_VERSION"", ""line"": ...",v0.4.22+commit.4cb486ee,,bzzr://9bf1e16c15b574a949b3e93d0ad05b9d5b8398d...
1,QUIK_QUIZ,QUIK_QUIZ.sol,0x27f2bf478f7d0c431328a56005b68432d18f26c5,Solidity,pragma solidity ^0.4.25;\r\n\r\ncontract QUIK_...,"{""TOD"": [[{""defect"": ""Transaction_order_depend...","[{""defect"": ""Transaction_order_dependency"", ""t...","[{""check"": ""external-function"", ""impact"": ""Opt...","[{""error"": ""Integer Underflow."", ""line"": 8, ""l...","[{""rule"": ""SOLIDITY_ADDRESS_HARDCODED"", ""line""...",v0.4.25+commit.59dbf8f1,,bzzr://ae1b8bc77c19b881d850b05812f4f1906ac65b0...
2,HodlerInvestmentClub,HodlerInvestmentClub.sol,0x7bd52bdff0acf4e18dd80c6ee86db205d83f88ce,Solidity,pragma solidity ^0.4.18;\r\n/**\r\n * Holds fu...,"{""TD"": [[{""defect"": ""Dependency_of_timestamp"",...","[{""defect"": ""Frozen_Ether"", ""type"": ""Code_spec...","[{""check"": ""constable-states"", ""impact"": ""Opti...","[{""error"": ""Integer Overflow."", ""line"": 40, ""l...","[{""rule"": ""SOLIDITY_DEPRECATED_CONSTRUCTIONS"",...",v0.4.18+commit.9cf6e910,,bzzr://7e489af849d6d3d4ecd951f2f8e1f9286982325...
3,LuckyNumber,LuckyNumber.sol,0x3ac0d29eaf16eb423e07387274a05a1e16a8472b,Solidity,pragma solidity ^0.4.18;\r\n\r\n/**\r\n* Send ...,"{""UpS"": [[{""defect"": ""Unprotected_Suicide"", ""l...","[{""defect"": ""Leaking_to_arbitary_address"", ""ty...","[{""check"": ""arbitrary-send"", ""impact"": ""High"",...","[{""error"": ""Transaction-Ordering Dependency."",...","[{""rule"": ""SOLIDITY_PRAGMAS_VERSION"", ""line"": ...",v0.4.19+commit.c4cbbb05,,bzzr://b25167b26dd21d0705334e402b300ca36037e69...
4,TokenERC20,TokenERC20.sol,0xd70e66775a74a9aedeac6e28313e1033cd726552,Solidity,pragma solidity ^0.4.16;\r\n\r\n\r\n\r\ncontra...,"{""IOU"": [[{""defect"": ""Integer_overflow_and_und...","[{""defect"": ""Leaking_to_arbitary_address"", ""ty...","[{""check"": ""constable-states"", ""impact"": ""Opti...","[{""error"": ""Integer Underflow."", ""line"": 63, ""...","[{""rule"": ""SOLIDITY_ADDRESS_HARDCODED"", ""line""...",v0.4.19+commit.c4cbbb05,,bzzr://8626e638e1b9f4aafcab7372e5ea55969e0b4cc...
...,...,...,...,...,...,...,...,...,...,...,...,...,...
519,IFYKRYGE,IFYKRYGE.sol,0x1237b26652eebf1cb8f59e07e07101c0df4f60f6,Solidity,pragma solidity ^0.4.20;\r\n\r\ncontract IFYKR...,"{""TOD"": [[{""defect"": ""Transaction_order_depend...","[{""defect"": ""Transaction_order_dependency"", ""t...","[{""check"": ""external-function"", ""impact"": ""Opt...","[{""error"": ""Integer Underflow."", ""line"": 16, ""...","[{""rule"": ""SOLIDITY_PRAGMAS_VERSION"", ""line"": ...",v0.4.20+commit.3155dd80,,bzzr://5a0d61bd31dd69f7bd278ef1871667cb6c6d219...
520,Presale,Presale.sol,0xe4ceb5a09d7c38d91587716c6f3e27e3f83f13bd,Solidity,pragma solidity ^0.4.11;\r\n\r\ncontract Presa...,"{""TD"": [[{""defect"": ""Dependency_of_timestamp"",...","[{""defect"": ""Erroneous_constructor_name"", ""typ...","[{""check"": ""controlled-array-length"", ""impact""...","[{""error"": ""Integer Overflow."", ""line"": 8, ""le...","[{""rule"": ""SOLIDITY_PRAGMAS_VERSION"", ""line"": ...",v0.4.11+commit.68ef5810,,bzzr://1999e6638f603ceda638220cb6623b9ec7182c9...
521,EagleTurstMoney,EagleTurstMoney.sol,0xc51218a624584cad04716d689593b798741e4acb,Solidity,pragma solidity 0.4.24;\r\n\r\n // ...,"{""NC"": [[{""defect"": ""Nest_Call"", ""lines"": [71]...","[{""defect"": ""Nest_Call"", ""type"": ""Business_log...","[{""check"": ""arbitrary-send"", ""impact"": ""High"",...","[{""error"": ""Integer Overflow."", ""line"": 68, ""l...","[{""rule"": ""SOLIDITY_EXTRA_GAS_IN_LOOPS"", ""line...",v0.4.24+commit.e67f0147,MIT,bzzr://122a4c65707eabcb1463782efcef7fd89352ecc...
522,LuckyBar,LuckyBar.sol,0x398193d0f35a132b9d8f7252c29d3c269c6f9965,Solidity,pragma solidity ^0.4.24;\r\n//pragma experimen...,"{""IOU"": [[{""defect"": ""Integer_overflow_and_und...","[{""defect"": ""Bad_randomness"", ""type"": ""Busines...","[{""check"": ""weak-prng"", ""impact"": ""High"", ""con...","[{""error"": ""Transaction-Ordering Dependency."",...","[{""rule"": ""SOLIDITY_ADDRESS_HARDCODED"", ""line""...",v0.4.24+commit.e67f0147,,bzzr://bd8f5725df3758569a9bb9fcf2f7458c746f97b...
523,question_quest,question_quest.sol,0xa630823bd70ab8e8e2d6e62089d3837db1887bf6,Solidity,pragma solidity ^0.4.20;\r\n\r\ncontract quest...,"{""TOD"": [[{""defect"": ""Transaction_order_depend...","[{""defect"": ""Transaction_order_dependency"", ""t...","[{""check"": ""external-function"", ""impact"": ""Opt...","[{""error"": ""Integer Underflow."", ""line"": 16, ""...","[{""rule"": ""SOLIDITY_PRAGMAS_VERSION"", ""line"": ...",v0.4.20+commit.3155dd80,,bzzr://8e0f4394b9c2a4934f90dee27f3e8681f733444...

In [53]:
print(train['language'].unique())
print(test['language'].unique())
print(valid['language'].unique())

['Solidity']
['Solidity']
['Solidity']

In [55]:
print(train['compiler_version'].unique())
print(test['compiler_version'].unique())
print(valid['compiler_version'].unique())

['v0.4.22+commit.4cb486ee' 'v0.4.25+commit.59dbf8f1'
 'v0.4.18+commit.9cf6e910' 'v0.4.19+commit.c4cbbb05'
 'v0.5.16+commit.9c3226ce' 'v0.4.23+commit.124ca40d'
 'v0.6.12+commit.27d51765' 'v0.4.13+commit.fb4cb1a'
 'v0.4.24+commit.e67f0147' 'v0.4.20+commit.3155dd80'
 'v0.4.17+commit.bdeb9e52' 'v0.4.26+commit.4563c3fc'
 'v0.4.16+commit.d7661dd9' 'v0.8.7+commit.e28d00a7'
 'v0.4.25-nightly.2018.7.5+commit.b1ab81ef' 'v0.8.4+commit.c7e474f2'
 'v0.6.6+commit.6c089d02' 'v0.5.1+commit.c8a2cb62'
 'v0.4.20-nightly.2018.1.6+commit.2548228b' 'v0.5.7+commit.6da8b019'
 'v0.5.17+commit.d19bba13' 'v0.5.11+commit.c082d0b4'
 'v0.6.2+commit.bacdbe57' 'v0.5.15+commit.6a57276f'
 'v0.8.10+commit.fc410830' 'v0.7.5+commit.eb77ed08'
 'v0.4.21+commit.dfe3193c' 'v0.4.15+commit.bbb8e64f'
 'v0.4.14+commit.c2215d46' 'v0.5.12+commit.7709ece9'
 'v0.4.12+commit.194ff033' 'v0.5.8+commit.23d335f2'
 'v0.8.9+commit.e5eed63a' 'v0.4.19-nightly.2017.11.11+commit.284c3839'
 'v0.5.13+commit.5b0b510c' 'v0.8.3+commit.8d00100c'
 'v0.7.2+commit.51b20bc0' 'v0.7.6+commit.7338295f'
 'v0.4.11+commit.68ef5810' 'v0.8.6+commit.11564f7e'
 'v0.6.11+commit.5ef660b1' 'v0.8.0+commit.c7dfd78e'
 'v0.4.14-nightly.2017.7.31+commit.22326189' 'v0.6.9+commit.3e3065ac'
 'v0.4.24-nightly.2018.5.7+commit.6db7e09a' 'v0.7.4+commit.3f05b770'
 'v0.4.22-nightly.2018.3.7+commit.b5e804b8'
 'v0.4.16-nightly.2017.8.11+commit.c84de7fa' 'v0.8.1+commit.df193b15'
 'v0.5.14+commit.01f1aaa4']
['v0.4.20-nightly.2018.1.6+commit.2548228b' 'v0.4.22+commit.4cb486ee'
 'v0.4.25+commit.59dbf8f1' 'v0.4.20+commit.3155dd80'
 'v0.4.18+commit.9cf6e910' 'v0.4.16+commit.d7661dd9'
 'v0.4.19+commit.c4cbbb05' 'v0.4.21+commit.dfe3193c'
 'v0.4.24+commit.e67f0147' 'v0.4.26+commit.4563c3fc'
 'v0.6.12+commit.27d51765' 'v0.4.11+commit.68ef5810'
 'v0.4.25-nightly.2018.6.22+commit.9b67bdb3']
['v0.4.20+commit.3155dd80' 'v0.4.24+commit.e67f0147'
 'v0.4.25+commit.59dbf8f1' 'v0.4.18+commit.9cf6e910'
 'v0.4.19+commit.c4cbbb05' 'v0.4.21+commit.dfe3193c'
 'v0.4.23+commit.124ca40d' 'v0.8.4+commit.c7e474f2'
 'v0.4.16+commit.d7661dd9' 'v0.5.1+commit.c8a2cb62'
 'v0.5.7+commit.6da8b019' 'v0.5.17+commit.d19bba13'
 'v0.6.4+commit.1dca32f3' 'v0.5.8+commit.23d335f2'
 'v0.4.17+commit.bdeb9e52' 'v0.4.13+commit.fb4cb1a'
 'v0.7.2+commit.51b20bc0']

In [94]:
import random

random_row = random.randint(0, len(train) - 1)  # Generates a number between 10 and 50 (inclusive)
print("Random row:", random_row)

source_code = train.iloc[random_row]['source_code']
overlapping = train.iloc[random_row]['overlapping']
slither = train.iloc[random_row]['slither']
print("\nsource code: \n" + source_code + "\n" + "\noverlapping: \n" + overlapping + "\nslither: \n" + slither)

Random row: 253

source code:
/**
 * Source Code first verified at https://etherscan.io on Monday, May 20, 2019
 (UTC) */

pragma solidity ^0.4.23;

/**
 * @title ERC20 interface
 * @dev see https://github.com/ethereum/EIPs/issues/20
 */
contract ERC20Basic {
    function totalSupply() public view returns (uint256);
    function balanceOf(address who) public view returns (uint256);
    function transfer(address to, uint256 value) public returns (bool);
    event Transfer(address indexed from, address indexed to, uint256 value);
}


contract ERC20 is ERC20Basic {
    function allowance(address owner, address spender) public view returns (uint256);
    function transferFrom(address from, address to, uint256 value) public returns (bool);
    function approve(address spender, uint256 value) public returns (bool);
    event Approval(address indexed owner, address indexed spender, uint256 value);
}

contract MultiSend {
  event Multisended(uint256 total, address tokenAddress);
  function multiSend(address _token, address[] addresses, uint[] counts) public {
    uint total;
    ERC20 token = ERC20(_token);
    for(uint i = 0; i < addresses.length; i++) {
      require(token.transferFrom(msg.sender, addresses[i], counts[i]));
        total += counts[i];
    }
    emit Multisended(total,_token);
  }
  function multiSendEth(address[] addresses,uint[] counts) public payable {
    for(uint i = 0; i < addresses.length; i++) {
      addresses[i].transfer(counts[i]);
    }
  }
}

overlapping:
{"IOU": [[{"defect": "Integer_overflow_and_underflow", "lines": [33], "severity": "High", "tool": "soldetector", "type": "Code_specification"}, {"error": "Integer Overflow.", "level": "Warning", "line": 37, "tool": "oyente"}]], "NC": [[{"defect": "Nest_Call", "lines": [38], "severity": "High", "tool": "soldetector", "type": "Business_logic"}, {"check": "calls-loop", "confidence": "Medium", "impact": "Low", "lines": [39], "tool": "slither"}, {"line": 38, "rule": "SOLIDITY_TRANSFER_IN_LOOP", "severity": 2, "tool": "smartcheck"}]]}
slither:
[{"check": "arbitrary-send", "impact": "High", "confidence": "Medium", "lines": [{"MultiSend.sol": [39]}]}, {"check": "external-function", "impact": "Optimization", "confidence": "High", "lines": [{"MultiSend.sol": [32, 33, 34, 35, 36, 28, 29, 30, 31]}]}, {"check": "external-function", "impact": "Optimization", "confidence": "High", "lines": [{"MultiSend.sol": [21]}]}, {"check": "external-function", "impact": "Optimization", "confidence": "High", "lines": [{"MultiSend.sol": [37, 38, 39, 40, 41]}]}, {"check": "external-function", "impact": "Optimization", "confidence": "High", "lines": [{"MultiSend.sol": [12]}]}, {"check": "external-function", "impact": "Optimization", "confidence": "High", "lines": [{"MultiSend.sol": [13]}]}, {"check": "external-function", "impact": "Optimization", "confidence": "High", "lines": [{"MultiSend.sol": [22]}]}, {"check": "external-function", "impact": "Optimization", "confidence": "High", "lines": [{"MultiSend.sol": [14]}]}, {"check": "external-function", "impact": "Optimization", "confidence": "High", "lines": [{"MultiSend.sol": [20]}]}, {"check": "solc-version", "impact": "Informational", "confidence": "High", "lines": [{"MultiSend.sol": [5]}]}, {"check": "calls-loop", "impact": "Low", "confidence": "Medium", "lines": [{"MultiSend.sol": [39]}]}, {"check": "calls-loop", "impact": "Low", "confidence": "Medium", "lines": [{"MultiSend.sol": [32]}]}, {"check": "naming-convention", "impact": "Informational", "confidence": "High", "lines": [{"MultiSend.sol": [28]}]}]

# smart contract vulndb

In [77]:
import json

file_path = f"{cwd}\\smart-contract-vulndb\\dataset\\vulns-1.json"

data = []

with open(file_path, encoding="utf-8") as f:
    for line in f:
        try:
            json_obj = json.loads(line)  # Parse JSON from each line
            data.append(json_obj)
        except json.JSONDecodeError as e:
            print(f"Skipping invalid JSON: {e}")

print(f"Loaded {len(data)} JSON objects")

Loaded 25000 JSON objects

In [102]:
import random
from IPython.display import Markdown

random_row = random.randint(0, len(data) - 1)  # Generates a number between 10 and 50 (inclusive)
print("Random row:", random_row)

# Pretty-printing the JSON
pretty_json = json.dumps(data[random_row], indent=4)
print(pretty_json)

# Example Markdown content
md_content = data[random_row]['body']

Markdown(md_content)

Random row: 2399
{
    "title": "6.10 maxAmount Can Be Circumvented",
    "severity": "medium",
    "body": "Design Medium Version 1 Code Corrected\n\nWhen opening a credit account, a check of the amount invested is performed:\n\n```\nrequire(\namount >= minAmount && amount <= maxAmount,\nErrors.CM_INCORRECT_AMOUNT\n);\n```\nBy limiting the amount originally invested, one can limit the amount of leverage that can be borrowed by\nthe pool. However, this limitation can be circumvented as follows:\n\n```\n1.The user opens an account with an allowed account.\n2.She calls CreditManager.addCollateral.\n3.She calls increaseBorrowedAmount.\n```\nNote, that addCollateral does not perform any checks and increaseBorrowedAmount only checks\nthat the borrowed amount does not turn the account unhealthy.\n\nCode Corrected:\n\nThe implementation has been extended to prevent increasing the borrowed amount more than the\npredetermined maximum:\n\n\n```\nrequire(\nborrowedAmount.add(amount) <\nmaxAmount.mul(maxLeverageFactor).div(\nConstants.LEVERAGE_DECIMALS\n),\nErrors.CM_INCORRECT_AMOUNT\n);\n```",
    "dataSource": {
        "name": "ChainSecurity/ChainSecurity_Gearbox_Protocol_Gearbox_audit_Dec-13th-2021.pdf",
        "url": "https://chainsecurity.com/wp-content/uploads/2021/12/ChainSecurity_Gearbox_Protocol_Gearbox_audit_Dec-13th-2021.pdf",
        "repo": "https://chainsecurity.com/wp-content/uploads/2021/12/ChainSecurity_Gearbox_Protocol_Gearbox_audit_Dec-13th-2021.pdf"
    }
}

Design Medium Version 1 Code Corrected

When opening a credit account, a check of the amount invested is performed:

```
require(
amount >= minAmount && amount <= maxAmount,
Errors.CM_INCORRECT_AMOUNT
);
```
By limiting the amount originally invested, one can limit the amount of leverage that can be borrowed by
the pool. However, this limitation can be circumvented as follows:

```
1.The user opens an account with an allowed account.
2.She calls CreditManager.addCollateral.
3.She calls increaseBorrowedAmount.
```
Note, that addCollateral does not perform any checks and increaseBorrowedAmount only checks
that the borrowed amount does not turn the account unhealthy.

Code Corrected:

The implementation has been extended to prevent increasing the borrowed amount more than the
predetermined maximum:


```
require(
borrowedAmount.add(amount) <
maxAmount.mul(maxLeverageFactor).div(
Constants.LEVERAGE_DECIMALS
),
Errors.CM_INCORRECT_AMOUNT
);
```

# Verified Smart Contract Code Comments

In [112]:
import pandas as pd
import os

cwd = os.getcwd()

# train = pd.read_parquet(f'{cwd}\\Verified-Smart-Contract-Code-Comments\\train')
test = pd.read_parquet(f'{cwd}\\Verified-Smart-Contract-Code-Comments\\test')
# valid = pd.read_parquet(f'{cwd}\\Verified-Smart-Contract-Code-Comments\\validation')

In [118]:
test

,contract_name,file_path,contract_address,language,class_name,class_code,class_documentation,class_documentation_type,func_name,func_code,func_documentation,func_documentation_type,compiler_version,license_type,swarm_source
0,B26_DevelopmentFund,B26_DevelopmentFund.sol,0x8781e1014aa5abbce363246b5aee249723bf9cf5,Solidity,Ownable,contract Ownable {\r\n address public owner ;...,/**\r\n * @title Ownable\r\n * @dev The Ownabl...,NatSpecMultiLine,transferOwnership,function transferOwnership(address newOwner) o...,/**\r\n * @dev Allows the current owner to tra...,NatSpecMultiLine,v0.7.0+commit.9e61f92b,BSD-3-Clause,ipfs://c771d4fee684817ed78447d91a4d700be6ed224...
1,RewardsType2,/Users/kstasi/Documents/side/dANT/contracts/Re...,0x666e6748db572ebc3ae40e4ce7748bc9be7a5aae,Solidity,ReferralTree,contract ReferralTree is AccessControl {\n ...,,,changeAdmin,function changeAdmin(address _newAdmin) public...,/// @dev Allows an admin to reanonce the DEFAU...,NatSpecSingleLine,v0.6.2+commit.bacdbe57,,
2,RewardsType2,/Users/kstasi/Documents/side/dANT/contracts/Re...,0x666e6748db572ebc3ae40e4ce7748bc9be7a5aae,Solidity,ReferralTree,contract ReferralTree is AccessControl {\n ...,,,setReferral,"function setReferral(address _referrer, addres...",/// @dev Allows a farming contract to set the ...,NatSpecSingleLine,v0.6.2+commit.bacdbe57,,
3,RewardsType2,/Users/kstasi/Documents/side/dANT/contracts/Re...,0x666e6748db572ebc3ae40e4ce7748bc9be7a5aae,Solidity,ReferralTree,contract ReferralTree is AccessControl {\n ...,,,removeReferralReward,function removeReferralReward(ReferralRewards ...,/// @dev Allows an admin to remove the referra...,NatSpecSingleLine,v0.6.2+commit.bacdbe57,,
4,RewardsType2,/Users/kstasi/Documents/side/dANT/contracts/Re...,0x666e6748db572ebc3ae40e4ce7748bc9be7a5aae,Solidity,ReferralTree,contract ReferralTree is AccessControl {\n ...,,,addReferralReward,function addReferralReward(ReferralRewards _re...,/// @dev Allows an admin to add the referral r...,NatSpecSingleLine,v0.6.2+commit.bacdbe57,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
143075,AmateurPlatinumToken,AmateurPlatinumToken.sol,0x7c16eaa346edab35d4e41556ab88bd4f76d3f93d,Solidity,AmateurPlatinumToken,contract AmateurPlatinumToken is ERC20Interfac...,// -------------------------------------------...,LineComment,,function () public payable {\r\n revert...,// -------------------------------------------...,LineComment,v0.4.19+commit.c4cbbb05,,bzzr://c4939ac3f091b98547bec84cce22026ae38da36...
143076,AmateurPlatinumToken,AmateurPlatinumToken.sol,0x7c16eaa346edab35d4e41556ab88bd4f76d3f93d,Solidity,AmateurPlatinumToken,contract AmateurPlatinumToken is ERC20Interfac...,// -------------------------------------------...,LineComment,transferAnyERC20Token,function transferAnyERC20Token(address tokenAd...,// -------------------------------------------...,LineComment,v0.4.19+commit.c4cbbb05,,bzzr://c4939ac3f091b98547bec84cce22026ae38da36...
143077,Controller,contracts/interfaces/yearn/Strategy.sol,0x735f865031eeece8f545de42395e188df7f1e3de,Solidity,Strategy,interface Strategy {\n function want() exte...,,,withdraw,function withdraw(address) external;,// NOTE: must exclude any tokens used in the y...,LineComment,v0.5.17+commit.d19bba13,,
143078,Controller,contracts/interfaces/yearn/Strategy.sol,0x735f865031eeece8f545de42395e188df7f1e3de,Solidity,Strategy,interface Strategy {\n function want() exte...,,,withdraw,function withdraw(uint256) external;,// Controller | Vault role - withdraw should a...,LineComment,v0.5.17+commit.d19bba13,,
143079,Controller,contracts/interfaces/yearn/Strategy.sol,0x735f865031eeece8f545de42395e188df7f1e3de,Solidity,Strategy,interface Strategy {\n function want() exte...,,,withdrawAll,function withdrawAll() external returns (uint2...,// Controller | Vault role - withdraw should a...,LineComment,v0.5.17+commit.d19bba13,,

In [116]:
test.columns

Index(['contract_name', 'file_path', 'contract_address', 'language',
       'class_name', 'class_code', 'class_documentation',
       'class_documentation_type', 'func_name', 'func_code',
       'func_documentation', 'func_documentation_type', 'compiler_version',
       'license_type', 'swarm_source'],
      dtype='object')

In [165]:
import random

random_row = random.randint(0, len(train) - 1)  # Generates a number between 10 and 50 (inclusive)
# print("Random row:", random_row)

random_row = 1

source_code = test.iloc[random_row]['class_code']
contract_name = test.iloc[random_row]['contract_name']
contract_address = test.iloc[random_row]['contract_address']
print(source_code)
print(contract_name)
print(contract_address)

contract ReferralTree is AccessControl {
    using SafeMath for uint256;

    event ReferralAdded(address indexed referrer, address indexed referral);

    bytes32 public constant REWARDS_ROLE = keccak256("REWARDS_ROLE"); // Role for those who allowed to mint new tokens

    mapping(address => address) public referrals; // Referral addresses for each referrer
    mapping(address => bool) public registered; // Map to ensure if the referrer is in the tree
    mapping(address => address[]) public referrers; // List of referrer addresses for each referral
    ReferralRewards[] public referralRewards; // Referral reward contracts that are allowed to modify the tree
    address public treeRoot; // The root of the referral tree

    /// @dev Constructor that initializes the most important configurations.
    /// @param _treeRoot The root of the referral tree.
    constructor(address _treeRoot) public AccessControl() {
        treeRoot = _treeRoot;
        registered[_treeRoot] = true;
        _setupRole(DEFAULT_ADMIN_ROLE, _msgSender());
    }

    /// @dev Allows an admin to reanonce the DEFAULT_ADMIN_ROLE.
    /// @param _newAdmin Address of the new admin.
    function changeAdmin(address _newAdmin) public {
        require(
            hasRole(DEFAULT_ADMIN_ROLE, _msgSender()),
            "changeAdmin: bad role"
        );
        _setupRole(DEFAULT_ADMIN_ROLE, _newAdmin);
        renounceRole(DEFAULT_ADMIN_ROLE, _msgSender());
    }

    /// @dev Allows a farming contract to set the users referral.
    /// @param _referrer Address of the referred user.
    /// @param _referral Address of the refferal.
    function setReferral(address _referrer, address _referral) public {
        require(hasRole(REWARDS_ROLE, _msgSender()), "setReferral: bad role");
        require(_referrer != address(0), "setReferral: bad referrer");
        if (!registered[_referrer]) {
            require(
                registered[_referral],
                "setReferral: not registered referral"
            );
            referrals[_referrer] = _referral;
            registered[_referrer] = true;
            referrers[_referral].push(_referrer);
            emit ReferralAdded(_referrer, _referral);
        }
    }

    /// @dev Allows an admin to remove the referral rewards contract from trusted list.
    /// @param _referralRewards Contract that manages referral rewards.
    function removeReferralReward(ReferralRewards _referralRewards) public {
        require(
            hasRole(DEFAULT_ADMIN_ROLE, _msgSender()),
            "setReferral: bad role"
        );
        for (uint256 i = 0; i < referralRewards.length; i++) {
            if (_referralRewards == referralRewards[i]) {
                uint256 lastIndex = referralRewards.length - 1;
                if (i != lastIndex) {
                    referralRewards[i] = referralRewards[lastIndex];
                }
                referralRewards.pop();
                revokeRole(REWARDS_ROLE, address(_referralRewards));
                break;
            }
        }
    }

    /// @dev Allows an admin to add the referral rewards contract from trusted list.
    /// @param _referralRewards Contract that manages referral rewards.
    function addReferralReward(ReferralRewards _referralRewards) public {
        require(
            hasRole(DEFAULT_ADMIN_ROLE, _msgSender()),
            "setReferral: bad role"
        );
        _setupRole(REWARDS_ROLE, address(_referralRewards));
        referralRewards.push(_referralRewards);
    }

    /// @dev Allows a user to claim all the dividends in all trusted products.
    function claimAllDividends() public {
        for (uint256 i = 0; i < referralRewards.length; i++) {
            ReferralRewards referralReward = referralRewards[i];
            if (referralReward.getReferralReward(_msgSender()) > 0) {
                referralReward.claimAllDividends(_msgSender());
            }
        }
    }

    /// @dev Returns user referrals up to the required depth.
    /// @param _referrer Address of referrer.
    /// @param _referDepth Number of referrals to be returned.
    /// @return List of user referrals.
    function getReferrals(address _referrer, uint256 _referDepth)
        public
        view
        returns (address[] memory)
    {
        address[] memory referralsTree = new address[](_referDepth);
        address referrer = _referrer;
        for (uint256 i = 0; i < _referDepth; i++) {
            referralsTree[i] = referrals[referrer];
            referrer = referralsTree[i];
        }
        return referralsTree;
    }

    /// @dev Returns user referrals up to the required depth.
    /// @param _referral Address of referral.
    /// @return List of user referrers.
    function getReferrers(address _referral)
        public
        view
        returns (address[] memory)
    {
        return referrers[_referral];
    }

    /// @dev Returns total user's referral reward.
    /// @param _user Address of the user.
    /// @return Total user's referral reward.
    function getUserReferralReward(address _user)
        public
        view
        returns (uint256)
    {
        uint256 amount = 0;
        for (uint256 i = 0; i < referralRewards.length; i++) {
            ReferralRewards referralReward = referralRewards[i];
            amount = amount.add(referralReward.getReferralReward(_user));
        }
        return amount;
    }

    /// @dev Returns trusted referral reward contracts.
    /// @return List of trusted referral reward contracts.
    function getReferralRewards()
        public
        view
        returns (ReferralRewards[] memory)
    {
        return referralRewards;
    }
}
RewardsType2
0x666e6748db572ebc3ae40e4ce7748bc9be7a5aae

In [163]:
rows = test[test['contract_name'] == 'RewardsType2']
rows

,contract_name,file_path,contract_address,language,class_name,class_code,class_documentation,class_documentation_type,func_name,func_code,func_documentation,func_documentation_type,compiler_version,license_type,swarm_source
1,RewardsType2,/Users/kstasi/Documents/side/dANT/contracts/Re...,0x666e6748db572ebc3ae40e4ce7748bc9be7a5aae,Solidity,ReferralTree,contract ReferralTree is AccessControl {\n ...,,,changeAdmin,function changeAdmin(address _newAdmin) public...,/// @dev Allows an admin to reanonce the DEFAU...,NatSpecSingleLine,v0.6.2+commit.bacdbe57,,
2,RewardsType2,/Users/kstasi/Documents/side/dANT/contracts/Re...,0x666e6748db572ebc3ae40e4ce7748bc9be7a5aae,Solidity,ReferralTree,contract ReferralTree is AccessControl {\n ...,,,setReferral,"function setReferral(address _referrer, addres...",/// @dev Allows a farming contract to set the ...,NatSpecSingleLine,v0.6.2+commit.bacdbe57,,
3,RewardsType2,/Users/kstasi/Documents/side/dANT/contracts/Re...,0x666e6748db572ebc3ae40e4ce7748bc9be7a5aae,Solidity,ReferralTree,contract ReferralTree is AccessControl {\n ...,,,removeReferralReward,function removeReferralReward(ReferralRewards ...,/// @dev Allows an admin to remove the referra...,NatSpecSingleLine,v0.6.2+commit.bacdbe57,,
4,RewardsType2,/Users/kstasi/Documents/side/dANT/contracts/Re...,0x666e6748db572ebc3ae40e4ce7748bc9be7a5aae,Solidity,ReferralTree,contract ReferralTree is AccessControl {\n ...,,,addReferralReward,function addReferralReward(ReferralRewards _re...,/// @dev Allows an admin to add the referral r...,NatSpecSingleLine,v0.6.2+commit.bacdbe57,,
5,RewardsType2,/Users/kstasi/Documents/side/dANT/contracts/Re...,0x666e6748db572ebc3ae40e4ce7748bc9be7a5aae,Solidity,ReferralTree,contract ReferralTree is AccessControl {\n ...,,,claimAllDividends,function claimAllDividends() public {\n ...,/// @dev Allows a user to claim all the divide...,NatSpecSingleLine,v0.6.2+commit.bacdbe57,,
6,RewardsType2,/Users/kstasi/Documents/side/dANT/contracts/Re...,0x666e6748db572ebc3ae40e4ce7748bc9be7a5aae,Solidity,ReferralTree,contract ReferralTree is AccessControl {\n ...,,,getReferrals,"function getReferrals(address _referrer, uint2...",/// @dev Returns user referrals up to the requ...,NatSpecSingleLine,v0.6.2+commit.bacdbe57,,
7,RewardsType2,/Users/kstasi/Documents/side/dANT/contracts/Re...,0x666e6748db572ebc3ae40e4ce7748bc9be7a5aae,Solidity,ReferralTree,contract ReferralTree is AccessControl {\n ...,,,getReferrers,function getReferrers(address _referral)\n ...,/// @dev Returns user referrals up to the requ...,NatSpecSingleLine,v0.6.2+commit.bacdbe57,,
8,RewardsType2,/Users/kstasi/Documents/side/dANT/contracts/Re...,0x666e6748db572ebc3ae40e4ce7748bc9be7a5aae,Solidity,ReferralTree,contract ReferralTree is AccessControl {\n ...,,,getUserReferralReward,function getUserReferralReward(address _user)\...,/// @dev Returns total user's referral reward....,NatSpecSingleLine,v0.6.2+commit.bacdbe57,,
9,RewardsType2,/Users/kstasi/Documents/side/dANT/contracts/Re...,0x666e6748db572ebc3ae40e4ce7748bc9be7a5aae,Solidity,ReferralTree,contract ReferralTree is AccessControl {\n ...,,,getReferralRewards,function getReferralRewards()\n public\...,/// @dev Returns trusted referral reward contr...,NatSpecSingleLine,v0.6.2+commit.bacdbe57,,
10,RewardsType2,/Users/kstasi/Documents/side/dANT/contracts/Re...,0x666e6748db572ebc3ae40e4ce7748bc9be7a5aae,Solidity,ReferralRewardsType2,contract ReferralRewardsType2 is ReferralRewar...,,,assessReferalDepositReward,function assessReferalDepositReward(address _r...,/// @dev Allows the main farming contract to a...,NatSpecSingleLine,v0.6.2+commit.bacdbe57,,
11,RewardsType2,/Users/kstasi/Documents/side/dANT/contracts/Re...,0x666e6748db572ebc3ae40e4ce7748bc9be7a5aae,Solidity,ReferralRewardsType2,contract ReferralRewardsType2 is ReferralRewar...,,,accumulateReward,function accumulateReward(address _user) inter...,/// @dev Update the staking referral reward fo...,NatSpecSingleLine,v0.6.2+commit.bacdbe57,,
12,RewardsType2,/Users/kstasi/Documents/side/dANT/contracts/Re...,0x666e6748db572ebc3ae40e4ce7748bc9be7a5aae,Solidity,ReferralRewardsType2,contract ReferralRewardsType2 is ReferralRewar...,,,removeDepositReward,function removeDepositReward(address _referrer...,/// @dev Allows the main farming contract to d...,NatSpecSingleLine,v0.6.2+commit.bacdbe57,,
13,RewardsType2,/Users/kstasi/Documents/side/dANT/contracts/Re...,0x666e6748db572ebc3ae40e4ce7748bc9be7a5aae,Solidity,ReferralRewardsType2,contract ReferralRewardsType2 is ReferralRewar...,,,getReferralReward,function getReferralReward(address _user)\n ...,/// @dev Returns referral reward.\n/// @param ...,NatSpecSingleLine,v0.6.2+commit.bacdbe57,,
62,RewardsType2,/Users/kstasi/Documents/side/dANT/contracts/Re...,0x666e6748db572ebc3ae40e4ce7748bc9be7a5aae,Solidity,RewardsType2,contract RewardsType2 is Rewards {\n event ...,,,unstake,function unstake(uint256 _amount) public {\n ...,/// @dev Allows to unstake deposit amount.\n//...,NatSpecSingleLine,v0.6.2+commit.bacdbe57,,
63,RewardsType2,/Users/kstasi/Documents/side/dANT/contracts/Re...,0x666e6748db572ebc3ae40e4ce7748bc9be7a5aae,Solidity,RewardsType2,contract RewardsType2 is Rewards {\n event ...,,,accumulateStakingReward,function accumulateStakingReward(address _user...,/// @dev Accumulate new reward and remove old ...,NatSpecSingleLine,v0.6.2+commit.bacdbe57,,
64,RewardsType2,/Users/kstasi/Documents/side/dANT/contracts/Re...,0x666e6748db572ebc3ae40e4ce7748bc9be7a5aae,Solidity,RewardsType2,contract RewardsType2 is Rewards {\n event ...,,,updateStakingReward,function updateStakingReward(address _user) in...,/// @dev Assess new reward.\n/// @param _user ...,NatSpecSingleLine,v0.6.2+commit.bacdbe57,,
65,RewardsType2,/Users/kstasi/Documents/side/dANT/contracts/Re...,0x666e6748db572ebc3ae40e4ce7748bc9be7a5aae,Solidity,RewardsType2,contract RewardsType2 is Rewards {\n event ...,,,executeUnstakes,function executeUnstakes(address _user) intern...,/// @dev Executes unstake requests if timelock...,NatSpecSingleLine,v0.6.2+commit.bacdbe57,,
66,RewardsType2,/Users/kstasi/Documents/side/dANT/contracts/Re...,0x666e6748db572ebc3ae40e4ce7748bc9be7a5aae,Solidity,RewardsType2,contract RewardsType2 is Rewards {\n event ...,,,getPendingReward,"function getPendingReward(address _user, bool ...",/// @dev Returns user's unclaimed reward.\n///...,NatSpecSingleLine,v0.6.2+commit.bacdbe57,,
67,RewardsType2,/Users/kstasi/Documents/side/dANT/contracts/Re...,0x666e6748db572ebc3ae40e4ce7748bc9be7a5aae,Solidity,RewardsType2,contract RewardsType2 is Rewards {\n event ...,,,getReward,function getReward(address _user)\n pub...,/// @dev Returns claimed and unclaimed user's ...,NatSpecSingleLine,v0.6.2+commit.bacdbe57,,
68,RewardsType2,/Users/kstasi/Documents/side/dANT/contracts/Re...,0x666e6748db572ebc3ae40e4ce7748bc9be7a5aae,Solidity,RewardsType2,contract RewardsType2 is Rewards {\n event ...,,,getRequestsLength,function getRequestsLength(address _user) publ...,// /// @dev Returns user's unstake requests le...,LineComment,v0.6.2+commit.bacdbe57,,
69,RewardsType2,/Users/kstasi/Documents/side/dANT/contracts/Re...,0x666e6748db572ebc3ae40e4ce7748bc9be7a5aae,Solidity,RewardsType2,contract RewardsType2 is Rewards {\n event ...,,,getTotalPendingRewards,function getTotalPendingRewards() public view ...,/// @dev Returns unclaimed rewards.\n/// @retu...,NatSpecSingleLine,v0.6.2+commit.bacdbe57,,
70,RewardsType2,/Users/kstasi/Documents/side/dANT/contracts/Re...,0x666e6748db572ebc3ae40e4ce7748bc9be7a5aae,Solidity,RewardsType2,contract RewardsType2 is Rewards {\n event ...,,,getTotalRewards,function getTotalRewards() public view returns...,/// @dev Returns assessed rewards.\n/// @retur...,NatSpecSingleLine,v0.6.2+commit.bacdbe57,,
71,RewardsType2,/Users/kstasi/Documents/side/dANT/contracts/Re...,0x666e6748db572ebc3ae40e4ce7748bc9be7a5aae,Solidity,RewardsType2,contract RewardsType2 is Rewards {\n event ...,,,handleDepositEnd,"function handleDepositEnd(address, uint256) in...",/// @dev Procces deposit and by returning depo...,NatSpecSingleLine,v0.6.2+commit.bacdbe57,,
115,RewardsType2,/Users/kstasi/Documents/side/dANT/contracts/Re...,0x666e6748db572ebc3ae40e4ce7748bc9be7a5aae,Solidity,ReferralRewards,contract ReferralRewards is Ownable {\n usi...,,,setBounds,function setBounds(uint256[amtLevels] memory _...,/// @dev Allows an owner to update bounds.\n//...,NatSpecSingleLine,v0.6.2+commit.bacdbe57,,
116,RewardsType2,/Users/kstasi/Documents/side/dANT/contracts/Re...,0x666e6748db572ebc3ae40e4ce7748bc9be7a5aae,Solidity,ReferralRewards,contract ReferralRewards is Ownable {\n usi...,,,setDepositRate,function setDepositRate(uint256[referDepth][am...,/// @dev Allows an owner to update deposit rat...,NatSpecSingleLine,v0.6.2+commit.bacdbe57,,
117,RewardsType2,/Users/kstasi/Documents/side/dANT/contracts/Re...,0x666e6748db572ebc3ae40e4ce7748bc9be7a5aae,Solidity,ReferralRewards,contract ReferralRewards is Ownable {\n usi...,,,setStakingRate,function setStakingRate(uint256[referDepth][am...,/// @dev Allows an owner to update staking rat...,NatSpecSingleLine,v0.6.2+commit.bacdbe57,,
118,RewardsType2,/Users/kstasi/Documents/side/dANT/contracts/Re...,0x666e6748db572ebc3ae40e4ce7748bc9be7a5aae,Solidity,ReferralRewards,contract ReferralRewards is Ownable {\n usi...,,,setReferral,"function setReferral(address _referrer, addres...",/// @dev Allows a farming contract to set user...,NatSpecSingleLine,v0.6.2+commit.bacdbe57,,
119,RewardsType2,/Users/kstasi/Documents/side/dANT/contracts/Re...,0x666e6748db572ebc3ae40e4ce7748bc9be7a5aae,Solidity,ReferralRewards,contract ReferralRewards is Ownable {\n usi...,,,assessReferalDepositReward,function assessReferalDepositReward(address _r...,/// @dev Allows the main farming contract to a...,NatSpecSingleLine,v0.6.2+commit.bacdbe57,,
120,RewardsType2,/Users/kstasi/Documents/side/dANT/contracts/Re...,0x666e6748db572ebc3ae40e4ce7748bc9be7a5aae,Solidity,ReferralRewards,contract ReferralRewards is Ownable {\n usi...,,,claimDividends,function claimDividends() public {\n cl...,/// @dev Allows a user to claim his dividends.,NatSpecSingleLine,v0.6.2+commit.bacdbe57,,
121,RewardsType2,/Users/kstasi/Documents/side/dANT/contracts/Re...,0x666e6748db572ebc3ae40e4ce7748bc9be7a5aae,Solidity,ReferralRewards,contract ReferralRewards is Ownable {\n usi...,,,claimAllDividends,function claimAllDividends(address _referral) ...,/// @dev Allows a referral tree to claim all t...,NatSpecSingleLine,v0.6.2+commit.bacdbe57,,
122,RewardsType2,/Users/kstasi/Documents/side/dANT/contracts/Re...,0x666e6748db572ebc3ae40e4ce7748bc9be7a5aae,Solidity,ReferralRewards,contract ReferralRewards is Ownable {\n usi...,,,removeDepositReward,function removeDepositReward(address _referrer...,/// @dev Allows to decrement staked amount tha...,NatSpecSingleLine,v0.6.2+commit.bacdbe57,,
123,RewardsType2,/Users/kstasi/Documents/side/dANT/contracts/Re...,0x666e6748db572ebc3ae40e4ce7748bc9be7a5aae,Solidity,ReferralRewards,contract ReferralRewards is Ownable {\n usi...,,,accumulateReward,function accumulateReward(address _user) inter...,/// @dev Update the staking referral reward fo...,NatSpecSingleLine,v0.6.2+commit.bacdbe57,,
124,RewardsType2,/Users/kstasi/Documents/side/dANT/contracts/Re...,0x666e6748db572ebc3ae40e4ce7748bc9be7a5aae,Solidity,ReferralRewards,contract ReferralRewards is Ownable {\n usi...,,,claimUserDividends,function claimUserDividends(address _user) int...,/// @dev Asses and distribute claimed dividend...,NatSpecSingleLine,v0.6.2+commit.bacdbe57,,
125,RewardsType2,/Users/kstasi/Documents/side/dANT/contracts/Re...,0x666e6748db572ebc3ae40e4ce7748bc9be7a5aae,Solidity,ReferralRewards,contract ReferralRewards is Ownable {\n usi...,,,getReferralReward,function getReferralReward(address _user)\n ...,/// @dev Returns referral reward.\n/// @param ...,NatSpecSingleLine,v0.6.2+commit.bacdbe57,,
126,RewardsType2,/Users/kstasi/Documents/side/dANT/contracts/Re...,0x666e6748db572ebc3ae40e4ce7748bc9be7a5aae,Solidity,ReferralRewards,contract ReferralRewards is Ownable {\n usi...,,,getReferral,function getReferral(address _user) public vie...,/// @dev Returns direct user referral.\n/// @p...,NatSpecSingleLine,v0.6.2+commit.bacdbe57,,
127,RewardsType2,/Users/kstasi/Documents/side/dANT/contracts/Re...,0x666e6748db572ebc3ae40e4ce7748bc9be7a5aae,Solidity,ReferralRewards,contract ReferralRewards is Ownable {\n usi...,,,getStakingRateRange,function getStakingRateRange(uint256 _referral...,/// @dev Returns stakong rate for the spesific...,NatSpecSingleLine,v0.6.2+commit.bacdbe57,,
128,RewardsType2,/Users/kstasi/Documents/side/dANT/contracts/Re...,0x666e6748db572ebc3ae40e4ce7748bc9be7a5aae,Solidity,ReferralRewards,contract ReferralRewards is Ownable {\n usi...,,,getDepositRate,function getDepositRate(uint256[] memory _refe...,/// @dev Returns deposit rate based on the spe...,NatSpecSingleLine,v0.6.2+commit.bacdbe57,,
129,RewardsType2,/Users/kstasi/Documents/side/dANT/contracts/Re...,0x666e6748db572ebc3ae40e4ce7748bc9be7a5aae,Solidity,ReferralRewards,contract ReferralRewards is Ownable {\n usi...,,,getDepositBounds,function getDepositBounds()\n public\n ...,/// @dev Returns limits of referral's stake us...,NatSpecSingleLine,v0.6.2+commit.bacdbe57,,
130,RewardsType2,/Users/kstasi/Documents/side/dANT/contracts/Re...,0x666e6748db572ebc3ae40e4ce7748bc9be7a5aae,Solidity,ReferralRewards,contract ReferralRewards is Ownable {\n usi...,,,getStakingRates,function getStakingRates()\n public\n ...,/// @dev Returns referral rates based on refer...,NatSpecSingleLine,v0.6.2+commit.bacdbe57,,
131,RewardsType2,/Users/kstasi/Documents/side/dANT/contracts/Re...,0x666e6748db572ebc3ae40e4ce7748bc9be7a5aae,Solidity,ReferralRewards,contract ReferralRewards is Ownable {\n usi...,,,getDepositRates,function getDepositRates()\n public\n ...,/// @dev Returns referral rates based on refer...,NatSpecSingleLine,v0.6.2+commit.bacdbe57,,
132,RewardsType2,/Users/kstasi/Documents/side/dANT/contracts/Re...,0x666e6748db572ebc3ae40e4ce7748bc9be7a5aae,Solidity,ReferralRewards,contract ReferralRewards is Ownable {\n usi...,,,getReferralAmounts,function getReferralAmounts(address _user)\n ...,/// @dev Returns amounts that generate reward ...,NatSpecSingleLine,v0.6.2+commit.bacdbe57,,
271,RewardsType2,/Users/kstasi/Documents/side/dANT/contracts/Re...,0x666e6748db572ebc3ae40e4ce7748bc9be7a5aae,Solidity,Rewards,abstract contract Rewards is Ownable {\n us...,,,setActive,function setActive(bool _isActive) public only...,/// @dev Allows an owner to stop or countinue ...,NatSpecSingleLine,v0.6.2+commit.bacdbe57,,
272,RewardsType2,/Users/kstasi/Documents/side/dANT/contracts/Re...,0x666e6748db572ebc3ae40e4ce7748bc9be7a5aae,Solidity,Rewards,abstract contract Rewards is Ownable {\n us...,,,setReferralRewards,function setReferralRewards(ReferralRewards _r...,/// @dev Allows an owner to update referral re...,NatSpecSingleLine,v0.6.2+commit.bacdbe57,,
273,RewardsType2,/Users/kstasi/Documents/side/dANT/contracts/Re...,0x666e6748db572ebc3ae40e4ce7748bc9be7a5aae,Solidity,Rewards,abstract contract Rewards is Ownable {\n us...,,,setDuration,function setDuration(uint256 _duration) public...,/// @dev Allows an owner to update duration of...,NatSpecSingleLine,v0.6.2+commit.bacdbe57,,
274,RewardsType2,/Users/kstasi/Documents/side/dANT/contracts/Re...,0x666e6748db572ebc3ae40e4ce7748bc9be7a5aae,Solidity,Rewards,abstract contract Rewards is Ownable {\n us...,,,setRewardPerSec,function setRewardPerSec(uint256 _rewardPerSec...,/// @dev Allows an owner to update reward rate...,NatSpecSingleLine,v0.6.2+commit.bacdbe57,,
275,RewardsType2,/Users/kstasi/Documents/side/dANT/contracts/Re...,0x666e6748db572ebc3ae40e4ce7748bc9be7a5aae,Solidity,Rewards,abstract contract Rewards is Ownable {\n us...,,,stakeFor,"function stakeFor(address _user, uint256 _amou...",/// @dev Allows to stake for the specific user...,NatSpecSingleLine,v0.6.2+commit.bacdbe57,,
276,RewardsType2,/Users/kstasi/Documents/side/dANT/contracts/Re...,0x666e6748db572ebc3ae40e4ce7748bc9be7a5aae,Solidity,Rewards,abstract contract Rewards is Ownable {\n us...,,,stake,"function stake(uint256 _amount, address _reffe...",/// @dev Allows to stake for themselves.\n/// ...,NatSpecSingleLine,v0.6.2+commit.bacdbe57,,
277,RewardsType2,/Users/kstasi/Documents/side/dANT/contracts/Re...,0x666e6748db572ebc3ae40e4ce7748bc9be7a5aae,Solidity,Rewards,abstract contract Rewards is Ownable {\n us...,,,proccessStake,function proccessStake(\n address _rece...,/// @dev Proccess the stake.\n/// @param _rece...,NatSpecSingleLine,v0.6.2+commit.bacdbe57,,
278,RewardsType2,/Users/kstasi/Documents/side/dANT/contracts/Re...,0x666e6748db572ebc3ae40e4ce7748bc9be7a5aae,Solidity,Rewards,abstract contract Rewards is Ownable {\n us...,,,accumulateStakingReward,function accumulateStakingReward(address _user...,/// @dev Accumulate new reward and remove old ...,NatSpecSingleLine,v0.6.2+commit.bacdbe57,,
279,RewardsType2,/Users/kstasi/Documents/side/dANT/contracts/Re...,0x666e6748db572ebc3ae40e4ce7748bc9be7a5aae,Solidity,Rewards,abstract contract Rewards is Ownable {\n us...,,,updateStakingReward,function updateStakingReward(address _user) in...,/// @dev Assess new reward.\n/// @param _user ...,NatSpecSingleLine,v0.6.2+commit.bacdbe57,,
280,RewardsType2,/Users/kstasi/Documents/side/dANT/contracts/Re...,0x666e6748db572ebc3ae40e4ce7748bc9be7a5aae,Solidity,Rewards,abstract contract Rewards is Ownable {\n us...,,,handleDepositEnd,"function handleDepositEnd(address _user, uint2...",/// @dev Procces deposit and by returning depo...,NatSpecSingleLine,v0.6.2+commit.bacdbe57,,
281,RewardsType2,/Users/kstasi/Documents/side/dANT/contracts/Re...,0x666e6748db572ebc3ae40e4ce7748bc9be7a5aae,Solidity,Rewards,abstract contract Rewards is Ownable {\n us...,,,safeTokenTransfer,"function safeTokenTransfer(address _to, uint25...",/// @dev Safe token transfer.\n/// @param _to ...,NatSpecSingleLine,v0.6.2+commit.bacdbe57,,
282,RewardsType2,/Users/kstasi/Documents/side/dANT/contracts/Re...,0x666e6748db572ebc3ae40e4ce7748bc9be7a5aae,Solidity,Rewards,abstract contract Rewards is Ownable {\n us...,,,getPendingReward,"function getPendingReward(address _user, bool ...",/// @dev Returns user's unclaimed reward.\n///...,NatSpecSingleLine,v0.6.2+commit.bacdbe57,,
283,RewardsType2,/Users/kstasi/Documents/side/dANT/contracts/Re...,0x666e6748db572ebc3ae40e4ce7748bc9be7a5aae,Solidity,Rewards,abstract contract Rewards is Ownable {\n us...,,,getReward,function getReward(address _user)\n pub...,/// @dev Returns claimed and unclaimed user's ...,NatSpecSingleLine,v0.6.2+commit.bacdbe57,,
284,RewardsType2,/Users/kstasi/Documents/side/dANT/contracts/Re...,0x666e6748db572ebc3ae40e4ce7748bc9be7a5aae,Solidity,Rewards,abstract contract Rewards is Ownable {\n us...,,,getReferralStakes,function getReferralStakes(address[] memory _r...,/// @dev Returns referral stakes.\n/// @param ...,NatSpecSingleLine,v0.6.2+commit.bacdbe57,,
285,RewardsType2,/Users/kstasi/Documents/side/dANT/contracts/Re...,0x666e6748db572ebc3ae40e4ce7748bc9be7a5aae,Solidity,Rewards,abstract contract Rewards is Ownable {\n us...,,,getReferralStake,function getReferralStake(address _referral) p...,/// @dev Returns referral stake.\n/// @param _...,NatSpecSingleLine,v0.6.2+commit.bacdbe57,,
286,RewardsType2,/Users/kstasi/Documents/side/dANT/contracts/Re...,0x666e6748db572ebc3ae40e4ce7748bc9be7a5aae,Solidity,Rewards,abstract contract Rewards is Ownable {\n us...,,,getEstimated,function getEstimated(uint256 _delta) public v...,/// @dev Returns approximate reward assessed i...,NatSpecSingleLine,v0.6.2+commit.bacdbe57,,
287,RewardsType2,/Users/kstasi/Documents/side/dANT/contracts/Re...,0x666e6748db572ebc3ae40e4ce7748bc9be7a5aae,Solidity,Rewards,abstract contract Rewards is Ownable {\n us...,,,getDeposit,"function getDeposit(address _user, uint256 _id...",/// @dev Returns user's deposit by id.\n/// @p...,NatSpecSingleLine,v0.6.2+commit.bacdbe57,,