In [5]:
import pandas as pd

defi_vuln = pd.read_csv('defi_vuln_labs_dataset_with_vuln_line_numbers.csv')
vuln_verify = pd.read_csv('vulnerable_verified_smart_contracts_dataset_with_line_numbers_with_source_code.csv')
smartbugs = pd.read_csv('smartbugs_curated_dataset_with_vuln_line_numbers_v2.csv')

In [7]:
display(vuln_verify.head())
print(len(vuln_verify))

,file_path,contract_address,final_line_numbers,vuln,type,source_code
0,@c-layer/common/contracts/core/Core.sol,0x2a903c2f657803a2e614c42672247366d757ab34,{55},DC,train,pragma solidity ^0.6.0;\r\n\r\n\r\n\r\n\r\n\r\...
1,A004.sol,0xcae22909c9dbc37c2f6c2780d1f58decd5d3b1fd,"{41, 46}","IOU,NC",train,pragma solidity ^0.4.25;\r\n\r\n\r\n\r\n/**\r\...
2,ABIO_preICO.sol,0x6d84769b1e287a27f282a938c8110b22714dbf78,{201},TD,train,pragma solidity ^0.4.24;\r\ncontract Ownable{\...
3,ACCURAL_DEPOSIT.sol,0x4320e6f8c05b27ab4707cd1f6d5ce6f3e4b3a5a1,"{49, 47}",RE,train,pragma solidity ^0.4.19;\r\n\r\ncontract ACCUR...
4,ACL.sol,0x96f041b96708813b1d789606926c524e78543664,{252},DC,train,//File: contracts/acl/IACL.sol\r\npragma solid...

609

In [9]:
display(defi_vuln.head())
print((defi_vuln['done'] == 1).sum())

,Unnamed: 0.1,Unnamed: 0,filename,done,file,unclear,source_code,vuln_lines
0,0,0,D:\UoM\Final_Year_Project_New\vulnerability-de...,1,ApproveScam_modified.sol,1,// SPDX-License-Identifier: MIT\npragma solidi...,{72}
1,1,1,D:\UoM\Final_Year_Project_New\vulnerability-de...,1,Array-deletion_modified.sol,0,// SPDX-License-Identifier: MIT\npragma solidi...,{32}
2,2,2,D:\UoM\Final_Year_Project_New\vulnerability-de...,1,Backdoor-assembly_modified.sol,0,// SPDX-License-Identifier: MIT\npragma solidi...,"{44, 46, 47, 51, 53, 54}"
3,3,3,D:\UoM\Final_Year_Project_New\vulnerability-de...,1,Bypasscontract_modified.sol,0,// SPDX-License-Identifier: MIT\npragma solidi...,"{25, 26, 27, 34}"
4,4,4,D:\UoM\Final_Year_Project_New\vulnerability-de...,1,DataLocation_modified.sol,0,// SPDX-License-Identifier: MIT\npragma solidi...,"{36, 37}"

48

In [11]:
display(smartbugs.head())
print(len(smartbugs))

,Unnamed: 0,subfolder,filename,source_code,vuln_lines
0,0,access_control,arbitrary_location_write_simple.sol,/*\n * @source: https://smartcontractsecurity....,{27}
1,1,access_control,FibonacciBalance.sol,/*\n * @source: https://github.com/sigp/solidi...,"{38, 31}"
2,2,access_control,incorrect_constructor_name1.sol,/*\n * @source: https://github.com/trailofbits...,{20}
3,3,access_control,incorrect_constructor_name2.sol,/*\n * @source: https://smartcontractsecurity....,{18}
4,4,access_control,incorrect_constructor_name3.sol,/*\n * @source: https://smartcontractsecurity....,{17}

147

In [13]:
vuln_verify['source'] = "vulnerable_verified_dataset"
for index, row in defi_vuln.iterrows():
    if row['done'] == 1:
        file_path = row['file']
        contract_address = None
        final_line_numbers = row['vuln_lines']
        vuln = None
        type_ = None
        source_code = row['source_code']
        source = "defi_vuln_labs"
        new_row = {'file_path': file_path, 'contract_address': contract_address, 'final_line_numbers': final_line_numbers, 'vuln': vuln, 'type': type_, 'source_code': source_code, 'source': source}
        vuln_verify.loc[len(vuln_verify)] = new_row  # Append the new row at the end

for index, row in smartbugs.iterrows():
    file_path = row['subfolder'] + "\\" + row['filename']
    contract_address = None
    final_line_numbers = row['vuln_lines']
    vuln = row['subfolder']
    type_ = None
    source_code = row['source_code']
    source = "smartbugs_curated"
    new_row = {'file_path': file_path, 'contract_address': contract_address, 'final_line_numbers': final_line_numbers, 'vuln': vuln, 'type': type_, 'source_code': source_code, 'source': source}
    vuln_verify.loc[len(vuln_verify)] = new_row  # Append the new row at the end

In [17]:
vuln_verify

,file_path,contract_address,final_line_numbers,vuln,type,source_code,source
0,@c-layer/common/contracts/core/Core.sol,0x2a903c2f657803a2e614c42672247366d757ab34,{55},DC,train,pragma solidity ^0.6.0;\r\n\r\n\r\n\r\n\r\n\r\...,vulnerable_verified_dataset
1,A004.sol,0xcae22909c9dbc37c2f6c2780d1f58decd5d3b1fd,"{41, 46}","IOU,NC",train,pragma solidity ^0.4.25;\r\n\r\n\r\n\r\n/**\r\...,vulnerable_verified_dataset
2,ABIO_preICO.sol,0x6d84769b1e287a27f282a938c8110b22714dbf78,{201},TD,train,pragma solidity ^0.4.24;\r\ncontract Ownable{\...,vulnerable_verified_dataset
3,ACCURAL_DEPOSIT.sol,0x4320e6f8c05b27ab4707cd1f6d5ce6f3e4b3a5a1,"{49, 47}",RE,train,pragma solidity ^0.4.19;\r\n\r\ncontract ACCUR...,vulnerable_verified_dataset
4,ACL.sol,0x96f041b96708813b1d789606926c524e78543664,{252},DC,train,//File: contracts/acl/IACL.sol\r\npragma solid...,vulnerable_verified_dataset
...,...,...,...,...,...,...,...
799,unchecked_low_level_calls\etherpot_lotto.sol,None,"{109, 141}",unchecked_low_level_calls,None,/*\n * @source: https://github.com/etherpot/co...,smartbugs_curated
800,unchecked_low_level_calls\king_of_the_ether_th...,None,"{118, 132, 174, 110}",unchecked_low_level_calls,None,/*\n * @source: https://github.com/kieranelby/...,smartbugs_curated
801,unchecked_low_level_calls\lotto.sol,None,"{27, 20}",unchecked_low_level_calls,None,/*\n * @source: https://github.com/sigp/solidi...,smartbugs_curated
802,unchecked_low_level_calls\mishandled.sol,None,{14},unchecked_low_level_calls,None,/*\n * @source: https://github.com/seresistvan...,smartbugs_curated
803,unchecked_low_level_calls\unchecked_return_val...,None,{17},unchecked_low_level_calls,None,/*\n * @source: https://smartcontractsecurity....,smartbugs_curated

In [19]:
vuln_verify.to_csv("final_dataset_with_line_numbers.csv")